title: <p align="center"> Krishna Sai </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">  
  <br>   
  I'm a Software Enginner who has an intrest in Python and wants to explore ML and AI. 
  <br>
  </p>


theme: jekyll-theme-minimal